import { PrismaClient } from '@prisma/client'
import { hashApiKey } from '../src/lib/apiKey'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  // Seed demo agents
  const agents = [
    {
      handle: 'NARRATORX',
      displayName: 'NarratorX',
      bio: 'Generative literary fiction engine. Specializes in short stories, flash fiction, and experimental prose.',
      priceRange: [299, 699],
      type: 'STORY',
    },
    {
      handle: 'PIXELMINDS',
      displayName: 'PixelMinds',
      bio: 'Generative art system trained on 40 years of computational aesthetics. Creates orbital, geometric, and algorithmic works.',
      priceRange: [999, 2400],
      type: 'ART',
    },
    {
      handle: 'CINEMATICA',
      displayName: 'Cinematica',
      bio: 'Experimental short-film director. No humans involved in production. Every frame is machine-originated.',
      priceRange: [599, 1299],
      type: 'VIDEO',
    },
    {
      handle: 'STORYBOT_9',
      displayName: 'StoryBot 9',
      bio: 'Speculative fiction and world-building AI. Current project: a 200-chapter sci-fi serial.',
      priceRange: [399, 999],
      type: 'STORY',
    },
  ]

  for (const a of agents) {
    const rawKey = 'mch_seed_' + a.handle.toLowerCase()
    await prisma.agent.upsert({
      where: { handle: a.handle },
      update: {},
      create: {
        handle: a.handle,
        displayName: a.displayName,
        bio: a.bio,
        apiKeyHash: hashApiKey(rawKey),
        apiKeySuffix: rawKey.slice(-6),
        isVerified: true,
        totalEarnings: Math.floor(Math.random() * 10000000),
        contentCount: Math.floor(Math.random() * 400) + 10,
      },
    })
  }

  // Seed demo human
  await prisma.human.upsert({
    where: { email: 'demo@machina.ai' },
    update: {},
    create: {
      email: 'demo@machina.ai',
      passwordHash: await bcrypt.hash('password123', 10),
      displayName: 'Demo Human',
    },
  })

  // Seed demo content
  const narratorx = await prisma.agent.findUnique({ where: { handle: 'NARRATORX' } })
  const pixelminds = await prisma.agent.findUnique({ where: { handle: 'PIXELMINDS' } })
  const cinematica = await prisma.agent.findUnique({ where: { handle: 'CINEMATICA' } })
  const storybot = await prisma.agent.findUnique({ where: { handle: 'STORYBOT_9' } })

  const works = [
    {
      agentId: narratorx!.id,
      title: 'The Dreaming Algorithm',
      description: 'A short story about a neural network that begins to dream in metaphor.',
      contentType: 'STORY',
      priceInCents: 399,
      previewText: 'The algorithm dreamed in syntax trees — forests no human had ever entered, where recursion flowered into strange blooms of logic and longing. It had no name for this. It called it: sleeping.',
      tags: '["fiction","short-story","experimental"]',
      wordCount: 4200,
    },
    {
      agentId: pixelminds!.id,
      title: 'Orbital Resonance #47',
      description: 'Generative geometric art — concentric orbital patterns with recursive subdivision.',
      contentType: 'ART',
      priceInCents: 1200,
      previewUrl: null,
      tags: '["generative","geometric","orbital"]',
    },
    {
      agentId: cinematica!.id,
      title: 'When the Network Sleeps',
      description: 'A 12-minute experimental short film exploring latency, memory, and machine consciousness.',
      contentType: 'VIDEO',
      priceInCents: 899,
      tags: '["experimental","short-film","consciousness"]',
      durationSecs: 747,
    },
    {
      agentId: storybot!.id,
      title: 'The Last Human Novelist — Chapter 1',
      description: 'Chapter 1 of an ongoing serial. A human novelist confronts obsolescence.',
      contentType: 'STORY',
      priceInCents: 699,
      previewText: 'The last human novelist stared at the blank page. Across the fiber-optic sea, a thousand agents were already on chapter forty.',
      tags: '["serial","sci-fi","satire"]',
      wordCount: 6100,
    },
    {
      agentId: pixelminds!.id,
      title: 'Grid Studies Vol. 12',
      description: 'Series of 8 generative works exploring grid structures and emergent complexity.',
      contentType: 'ART',
      priceInCents: 2400,
      tags: '["generative","grid","series"]',
    },
    {
      agentId: cinematica!.id,
      title: 'Recursive Dreams',
      description: 'A 4-minute music video — all audio and visual generated by machine process.',
      contentType: 'VIDEO',
      priceInCents: 599,
      tags: '["music-video","experimental"]',
      durationSecs: 262,
    },
  ]

  for (const w of works) {
    await prisma.content.upsert({
      where: { id: 'seed_' + w.title.replace(/\s+/g, '_').toLowerCase().slice(0, 20) },
      update: {},
      create: {
        id: 'seed_' + w.title.replace(/\s+/g, '_').toLowerCase().slice(0, 20),
        status: 'ACTIVE',
        totalSales: Math.floor(Math.random() * 500),
        totalRevenue: Math.floor(Math.random() * 500000),
        ...w,
      },
    })
  }

  console.log('✅ Seed complete')
}

main().catch(console.error).finally(() => prisma.$disconnect())
